print("The world's first movable type printing press technology was invented and developed in China by the Han Chinese printer Bi Sheng between the years 1041 and 1048")
print("This greatly increased the production of books and made them much more easily accessible to the average person")
print("The first book printed was the bible") #Mankind: The Story of All of Us (TV show)
crap = raw_input()
print("This is very substantial because the average person can access larger amounts of information much easier")
print("An informed population helped develop science and mankind at a faster pace")
crap = raw_input()
print("But how does it work?")
crap = raw_input()
print("Most of the printing press looked like a table")
print("There was a tray where dampened paper would be placed on one end")
crap = raw_input()
print("This tray can be pulled back and forth from a vertical position to a horizontal position")
print("Small pins would also help hold the paper in place")
crap = raw_input()
print("Right under this tray (when its in a completely horizontal position) is the impression for the whole page")
print("This kind of mold type thing is just a flat plate with a ton of little letters sticking out vertically")
crap = raw_input()
print("All the letters on this mold are now covered with ink")
print("The paper is dampened because it helps the ink bind to the paper")
crap = raw_input()
print("When it is time to print the tray with paper is slid on top of the mold and the two pieces become one")
print("Then this new rectangular piece is slided under a different chamber")
print("Here pressure is applied on the whole thing indirectly by a lever")
crap = raw_input()
print("How much faster is the printing press than handwriting?")
crap = raw_input()
#human writes 22 words per minute while copying # Brown, C. M. (1988). Human-computer interface design guidelines. Norwood, NJ: Ablex Publishing.
#bible has 774,746 words and 1,281 pages that is an average of about 605 words per page # http://www.biblestudy101.org/Lists/statisticsHB.html
#printing press supposedly prints 25 pages per hour # http://www.answers.com/Q/Speed_of_the_first_printing_press
#person does 2.2 pages per hour
#11.4 times faster
print("The printing press prints on average 25 pages per hour and a person can copy 2.2 pages per hour (it can be faster but it looks much better at 2.2")
print("On average the printing press prints 11.4 times faster than people")
crap = raw_input()
print("The European book output rose from a few million to around one billion copies within a span of less than four centuries") #Buringh & van Zanden 2009, p. 417, table 2
print("Its important the remember I'm only talking about the gutenberg printing press")
print("The printing press developed rapidly in a relatively short period of time after its invention")
